### ISSUE TITLE
First launch : docker dopp-api folder missing

### ISSUE THREAD

**Issue by sonde35** [youhgo/DOPP#1]
Hello,
I try to install and I had an error when trying to POST a file:
FileNotFoundError: [Errno 2] No such file or directory: '/python-docker/shared_files/depot/Collect_System.7z__1445'

After debug, it works by doing a "mkdir /python-docker/shared_files/depot" in the dopp-api docker.
Thanks

**Comment by youhgo** [comment]
Hey, thanks for the feedback

I added the creation of those folders, that should fixe the issue !

don't hesitate if you have any question or request 

Hugo
